const { Builder, By, Key, until } = require('selenium-webdriver');
const chrome = require('selenium-webdriver/chrome');
const axios = require('axios');
const fs = require('fs');
const path = require('path');
let counter = 1;

let text = "Your prompt goes here...";

async function generateAiArt(prompt) {
    let options = new chrome.Options();
    options.addArguments("--headless", "--disable-gpu", "--window-size=1920,1080", "--incognito");
    let driver = await new Builder()
        .forBrowser('chrome')
        .setChromeOptions(options)
        .build();

    try {
        await driver.get('https://replicate.com/stability-ai/stable-diffusion-3?prediction=jrdt4zf9anrm00cgeecvs7fhbr');

        let inputArea = await driver.wait(until.elementLocated(By.id('prompt')), 10000);
        await inputArea.clear();
        await inputArea.sendKeys(prompt);
        await driver.actions()
            .keyDown(Key.CONTROL)
            .sendKeys(Key.RETURN)
            .keyUp(Key.CONTROL)
            .perform();

        let imageElement = await driver.wait(until.elementLocated(By.xpath("//img[@data-testid='value-output-image']")), 60000);

        let imageUrl = await imageElement.getAttribute('src');
        let response = await axios.get(imageUrl, { responseType: 'arraybuffer' });
        const dir = './autogenerated';
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir);
        }

        const filePath = path.join(dir, `${counter}.webp`);
        fs.writeFileSync(filePath, response.data);
        counter++;
        console.log(`Image saved as '${filePath}'`);
    } finally {
        await driver.quit();
    }
    generateAiArt(text);
}

generateAiArt(text);
